### ISSUE TITLE
no error on empty result set. Is it ok?

### ISSUE THREAD

**Issue by cherryBaker** [georgysavva/scany#112]
Hi!
When query returns nothing I expect to get error pgx.ErrNoRows ("no rows in result set"). But there is not error. Is it bug of feature?

Example

```go
package main

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/georgysavva/scany/pgxscan"
	pgx "github.com/jackc/pgx/v4"
	"github.com/jackc/pgx/v4/pgxpool"
)

func main() {
	dsn := "DATABASE_URL"
	conn, err := pgx.Connect(context.Background(), dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close(context.Background())

	var id int64
	err = conn.QueryRow(context.Background(), "select id from user where id = 11111").Scan(&id)
	if err != nil {
		fmt.Printf("pgx: equal? %v\n", errors.Is(err, pgx.ErrNoRows))
	}

	ctx := context.Background()
	db, _ := pgxpool.Connect(ctx, dsn)

	var users []*User
	err = pgxscan.Select(ctx, db, &users, `SELECT * FROM user where id = 11111`)
	if err != nil {
		fmt.Printf("equal? %v\n", errors.Is(err, pgx.ErrNoRows))
	}
}

type User struct {
	ID   int64
	Name string
}

```
I get output
```
pgx: equal? true
```

**Comment by georgysavva** [comment]
Hi. This is not a bug; it's a feature. 

The `pgxscan.Select()` method you call is meant to get a list of rows. If there are no rows, the list is just empty. So it's expected and not an error. 

The only time scany returns `pgx.ErrNoRows` is when you call `pgxscan.ScaOne()` or `pgxscan.Get()`, with the latter being just a wrapper around the former. These two methods expect to get exactly one row, and if there are none, they produce `pgx.ErrNoRows`. The same logic is behind the native `conn.QueryRow()` you used above. You ask it to scan a row, but there is none, so it returns an error. 

Feel free to reopen if you have more questions.

**Comment by cherryBaker** [comment]
Thank you!
