### ISSUE TITLE
Roadmap: named parameters

### ISSUE THREAD

**Issue by jsumners** [georgysavva/scany#118]
For what it's worth, I started in on a library that does this (before I found the wiki here and saw it is on your todo list) at https://github.com/jsumners/go-namedlist . It mostly works, but definitely needs polishing.

**Comment by georgysavva** [comment]
Hi @jsumners, yes, this feature is on the roadmap, and there has even been an attempt to implement it by a contributor. I decided to postpone it for now for the sake of interface simplicity. If you feel like it, you can go ahead with maturing your library. It might be an excellent separate addition to what scany offers.
