### ISSUE TITLE
Thank you for this library

### ISSUE THREAD

**Issue by dclipca** [georgysavva/scany#12]
Thank you so much for building this library, it saved me a lot of time. You rock!

Does it support omitting certain properties from a struct?

**Comment by georgysavva** [comment]
@virtumonde Thanks for your warm words! 
Yes it does. you can do it via `db:"-"` struct tag, please see [this](https://pkg.go.dev/github.com/georgysavva/scany@v0.2.4/dbscan?tab=doc#hdr-Ignored_struct_fields) docs section for details and example.

@navirick Yep, apart from omitting struct fields, you can set a custom column name via `db` struct tag, see [this](https://pkg.go.dev/github.com/georgysavva/scany@v0.2.4/dbscan?tab=doc#hdr-Scanning_into_struct) docs section for details and example

**Comment by navirick** [comment]
@georgysavva Excellent. I tried that out and it works great. Very cool.
Question.. though it may not apply to this project.. is there any chance you'll add (or make another project) that allows the storage of a struct similar to how this is done? Seems like going both ways would be ideal when working with structs.

**Comment by georgysavva** [comment]
You mean when we have a struct filled with data and we want to save this data to the database?

I thought about implementing this actually. The only thing that stopped me is that different databases have a different symbol for query arguments:`$` for postgres, `?` for mysql and etc. 
It will require the user to configure this somehow and it will complicate the library, so I decided to not add it.

**Comment by georgysavva** [comment]
BTW I added the list of all features to the readme file.

**Comment by navirick** [comment]
Yah.. and that's a good point. Oddly I thought this was a library for pgx which was postgresql. I came to it from pgx.. but I see you support others as well. Until we have generics you would be stuck implementing db specific implementations. I am good with that :D. The name though.. scany.. may contradict the opposite direction, pushy or story... :D

**Comment by georgysavva** [comment]
I don't like the idea of db specific implementations. 
I have some plans for adding configuration ability for the user, maybe after this is implemented I can start thinking about this feature. 

Alternatively, we could use this approach:
For Postgres:
```
"INSERT INTO users (id, name, age) ($id, $name, $age)" -> "INSERT INTO users (id, name, age) ($1, $2, $3)" 
```
For MySQL:
```
"INSERT INTO users (id, name, age) (?id, ?name, ?age)" -> "INSERT INTO users (id, name, age) (?, ?, ?)" 
```
 For SQL server:
```
"INSERT INTO users (id, name, age) (@id, @name, @age)" -> "INSERT INTO users (id, name, age) (@p1, @p2, @p3)" 
```
So the query will contain named argument with the special symbol specific for the database of the user and scany library will detect this symbol and resolve it to the proper query, valid for this database.

This way scany doesn't need any configuration from the user, because it gets the special symbol in every query. 
But I have some doubts about this solution as well. Tell me what you think

**Comment by pashagolub** [comment]
Hello. Greetings and thanks for a great piece of code. 

Do you have any kind of answer how `scany` is similar/different to [`sqlx`](https://jmoiron.github.io/sqlx/)? 

Some of my projects are build with `sqlx`, but I want to switch to `pgx` and that's where `scany` arrives. :)

Thanks in advance!

**Comment by georgysavva** [comment]
@pashagolub Thanks for reaching out!

1. scany supports both `database/sql` and `pgx` native interface (when you use `pgx` as a standalone library, without `database/sql` layer). Also it can be extended to work with any db library. On the other hand, `sqlx` only works with `database/sql`.
2. In terms of scanning and mapping abilities, scany provides all features of `sqlx`.
3. Scany has a much simpler API/interface and much fewer concepts compared to `sqlx`, so I believe it should be easier to use.
4. Scany doesn't support the opposite direction of mapping when you insert data from your struct into the query, at least for now. We had a discussion about implementing this: https://github.com/georgysavva/scany/issues/12#issuecomment-682006759. `sqlx`has this feature. 

Those are the main points.

**Comment by anton7r** [comment]
> I don't like the idea of db specific implementations. I have some plans for adding configuration ability for the user, maybe after this is implemented I can start thinking about this feature.
> 
> Alternatively, we could use this approach: For Postgres:
> 
> ```
> "INSERT INTO users (id, name, age) ($id, $name, $age)" -> "INSERT INTO users (id, name, age) ($1, $2, $3)" 
> ```
> 
> For MySQL:
> 
> ```
> "INSERT INTO users (id, name, age) (?id, ?name, ?age)" -> "INSERT INTO users (id, name, age) (?, ?, ?)" 
> ```
> 
> For SQL server:
> 
> ```
> "INSERT INTO users (id, name, age) (@id, @name, @age)" -> "INSERT INTO users (id, name, age) (@p1, @p2, @p3)" 
> ```
> 
> So the query will contain named argument with the special symbol specific for the database of the user and scany library will detect this symbol and resolve it to the proper query, valid for this database.
> 
> This way scany doesn't need any configuration from the user, because it gets the special symbol in every query. But I have some doubts about this solution as well. Tell me what you think

@georgysavva are these named query parameters already implemented into scany? i could perhaps integrate my library (https://github.com/anton7r/pgxe) into scany.

**Comment by georgysavva** [comment]
Hey @anton7r. No, I actually haven't started working on this yet. So feel free to shoot a PR with your integration!

**Comment by anton7r** [comment]
@georgysavva yeah, opened it #71
