### ISSUE TITLE
Method Get Return error `scanning one: scanning: doing scan: starting: scany: to scan into a primitive type, columns number must be exactly 1, got: 15`

### ISSUE THREAD

**Issue by divir112** [georgysavva/scany#143]
The documentation says I can scan a row. Why is the error related to the number of columns

type TaskInfo struct {
	TaskID              sql.NullString  `db:"task_id"`
	ReleaseName         sql.NullString  `db:"release_name"`
	Platform            sql.NullString  `db:"platform"`
	Author              sql.NullString  `db:"author"`
	Status              sql.NullString  `db:"status"`
	Description         sql.NullString  `db:"description"`
	Metadata            Metadata        `db:"metadata" json:"metadata"`
	CreatedAt           sql.NullString  `db:"created_at"`
	FinishedAt          sql.NullString  `db:"finished_at"`
	ErrorMessage        sql.NullString  `db:"error_message"`
	WasRepeated         bool            `db:"was_repeated"`
	RepeatedChildTaskID sql.NullString  `db:"repeated_child_task_id"`
	URLListStatus       []URLListStatus `db:"url_list" json:"url_list,omitempty"`
	Completed           sql.NullInt32   `db:"completed"`
	Total               sql.NullInt32   `db:"total"`
}

sqlQuery := "SELECT th.task_id, th.release_name, th.platform, th.author, th.status, th.description, th.metadata, th.created_at, th.finished_at, th.error_message, th.was_repeated, th.repeated_child_task_id, th.url_list, completed, total FROM task_history th LEFT JOIN task_progress ON th.task_id = task_progress.task_id WHERE th.task_id = $1"

var taskInfo []*TaskInfo
err := pgxscan.Get(ctx, db, &taskInfo, sqlQuery) 
```

**Comment by georgysavva** [comment]
Hi, the reason you are getting this error is that you pass an array, `[]*TaskInfo`, to the `Get()` method, which is meant to get a single row, so it expects a struct. 

If you intended to scan a single row, you should do this:
```go
var taskInfo TaskInfo
err := pgxscan.Get(ctx, db, &taskInfo, sqlQuery)
```
But then you need to ensure that your `sqlQuery` always returns a single row.

If you meant to scan multiple rows, you should use the `Select()` method instead:
```go
var taskInfos []*TaskInfo
err := pgxscan.Select(ctx, db, &taskInfos, sqlQuery)
```

Feel free to reopen if you have any further question.
