### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by CthulhuDen** [georgysavva/scany#145]
Currently there seems to be no way to use scanny with huge resultsets without allocating all of the result structures at once. 

It would be nice if there was api like the following: provide pointer to a structure, and then call something like `func Next() bool`; and after each call structure would be filled with data from the new row? Or even, closer to the `database/sql`, after each `Next()` call to `Scan`, but that would maybe be slower because each time would need to inspect the destination anew.

**Comment by georgysavva** [comment]
Hi, Scany already supports this with its `RowScanner` API. This is the class the higher level APIs like `Get()` and `Select()` use. You can use it directly to control the `Next()` behavior. Here is an example: https://pkg.go.dev/github.com/georgysavva/scany/v2@v2.1.3/pgxscan#example-RowScanner.

Feel free to reopen if you have further questions.

**Comment by CthulhuDen** [comment]
Oh, I missed it. Thanks!
