### ISSUE TITLE
transaction support

### ISSUE THREAD

**Issue by AubSs** [georgysavva/scany#18]
Hi! Thank you for your library !
Do you have any plan of supporting native pgx transaction ? (like sqlx)

**Comment by georgysavva** [comment]
Hi, thanks for your question. It's already supported. 
When you call `pgxscan.Select()` or `pgxscan.Get()` you pass something that implements `pgxscan.Querier` interface and from the [docs](https://pkg.go.dev/github.com/georgysavva/scany@v0.2.5/pgxscan#Querier) for this interface: 
> Querier is something that pgxscan can query and get the pgx.Rows from. For example, it can be: *pgxpool.Pool, *pgx.Conn or pgx.Tx

So you can use all scany functions on transactions or database instances, it doesn't matter for this library.

Actually, I am going to spot more light on this in the `pgxscan` package documentation.

**Comment by georgysavva** [comment]
Here is the new docs for it:
https://pkg.go.dev/github.com/georgysavva/scany@v0.2.6/pgxscan#hdr-Querying_rows

**Comment by AubSs** [comment]
You rock ! thank you
