### ISSUE TITLE
Type does not implement 'Querier'

### ISSUE THREAD

**Issue by KirksFletcher** [georgysavva/scany#22]
Wanted to make a fork to test some extensions like Insert etc but it seem this build is not working. Passing a PGX connection or pool results in: Type does not implement 'Querier'

Type does not implement 'Querier' 
need method: Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error) 
have method: Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error)

A bit strange I must admit

**Comment by KirksFletcher** [comment]
Ignore me, broken import

**Comment by georgysavva** [comment]
Hi. Thanks for the issue, yes you must use pgx `v4`:
https://pkg.go.dev/github.com/georgysavva/scany@v0.2.6/pgxscan#hdr-Supported_pgx_version
