### ISSUE TITLE
Scanning into a pointer to string inside struct

### ISSUE THREAD

**Issue by pragyanaryal** [georgysavva/scany#23]
Hello, I read through the note in doc, but i need to implement some columns as null-able field. Is there any workaround to scan pointer to string using pgxscan ?

My Struct is as such
![image](https://user-images.githubusercontent.com/36224537/97797438-28eeec80-1c45-11eb-8b8d-5ed579572368.png)

It is able to scan to pointer in nested struct, which is of composite type, but is not able to scan to plain pointer to nil. Am I missing something ?

![image](https://user-images.githubusercontent.com/36224537/97797482-9438be80-1c45-11eb-870c-c6e32ec1d0bc.png)

**Comment by georgysavva** [comment]
Hi. Thanks for the issue. 
What you are asking for should work by default, without any workarounds. 
What exactly "note in the docs" you are talking about, can you give me the link?

BTW, can you send me the full code version with the struct definition, pgxscan call and the full error.

**Comment by pragyanaryal** [comment]
Hello, Sorry, It was my fault . Data type mismatch between db and go's code was causing the problem. I had implemented int on the database but the field was string on the go's side, upon changing, it behaves fine. It scans fine now as intended. The link in docs I was pointing towards was:
https://pkg.go.dev/github.com/georgysavva/scany/pgxscan#hdr-Note_about_pgx_custom_types

![image](https://user-images.githubusercontent.com/36224537/97800709-8ee86d80-1c5f-11eb-85e7-25e255bfd789.png)
 Upon reading, it cannot scan into pointer, I was deviated. 

Thanks, this is really nice package. :)
