### ISSUE TITLE
scany thinks it's scanning into a primitive type

### ISSUE THREAD

**Issue by dev-kittens** [georgysavva/scany#27]
i have this code: 

```go
type Instance struct {
	Domain       string `sql:"domain"`
	URL          string `sql:"url"`
	ClientID     string `sql:"client_id"`
	ClientSecret string `sql:"client_secret"`
}

func GetInstance(domain string) (i *Instance, err error) {
	err = pgxscan.Get(context.Background(), pool, &i, "select * from instances where domain = $1", domain)
	if errors.Is(err, pgx.ErrNoRows) {
		err = InstanceNotFound
	}
	return
}
```

i get the error: `scany: to scan into a primitive type, columns number must be exactly 1, got: 4`
what am I doing wrong here? this error doesn't seem correct (a struct is not a primitive type), and i'm pretty sure i'm using similar code (just with a different struct) elsewhere

**Comment by dev-kittens** [comment]
oh, I used pointers incorrectly. the fix was to use `i Instance`
still seems like an odd error message, tbh

**Comment by georgysavva** [comment]
Hi, @dev-kittens. Thanks for opening this issue. Yes, you are passing a pointer to a pointer. You need to remove the extra pointer.
BTW, I can see that you use `sql` struct tag, JFYI scany supports only `db` struct tag. Mapping won't work if you use `sql` word.

**Comment by dev-kittens** [comment]
> scany supports only `db` struct tag
ohh, this fixes some other issues i was having. thank you 👍
