### ISSUE TITLE
Nested/Embeded structs don't seem to work correctly

### ISSUE THREAD

**Issue by krazik-intuit** [georgysavva/scany#34]
I'm trying to switch from sqlx, I have nested structs for commonly used fields, these worked with sqlx.  you seem to have a function `initializeNested()` but it's called after the error, so not sure if it doesn't work or for something else?

`error scany: column: 'id': no corresponding field found, or it's unexported in...`

```
type AutoIncrIDField struct {
	ID uint32 `db:"id,primarykey,autoincrement" json:"id,omitempty"`
}
type Another struct {
	AutoIncrIDField
        SomeOtherID     uint32      `db:"some_other_id"`
}
```

I tried to poke around to see where to fix but not quite sure.  Usually you need to recurse into the child structs.

From another part of my code where I do this

```
func sqlMockFieldsFromStruct(inputStruct interface{}) []sqlMockField {
	result := []sqlMockField{}
	structValue := reflect.ValueOf(inputStructValue)
	structType := reflect.TypeOf(inputStructValue)

	for i := 0; i < structType.NumField(); i++ {
		fieldValue := structValue.Field(i)
		if structType.Field(i).Anonymous { // <<-- HERE
			result = append(result, sqlMockFieldsFromStruct(fieldValue.Interface())...)
		} else {
			result = append(result, sqlMockField{
				Field: structType.Field(i),
				Value: fieldValue,
			})
		}
	}
	return result
}
```

**Comment by krazik-intuit** [comment]
Also thank you for building this!

**Comment by krazik-intuit** [comment]
turns out this was the `,` in the tag. I've removed them since scany doesn't use.

**Comment by georgysavva** [comment]
Hi! Yes, scany doesn't support any `,` in the struct tag for now.

**Comment by krazik-intuit** [comment]
@georgysavva it's super simple to add support for tho.  I'm opening a PR should you want it.
