### ISSUE TITLE
Is there a way to specify a time zone when scanning postgres timestamp without time zone fields?

### ISSUE THREAD

**Issue by timuckun** [georgysavva/scany#65]
**To help with debugging please provide your code with all relevant information to scany.**
I have a query which selects one row from the database. This row has date fields in it. When the dates are scanned they end up as UTC dates

I would like to be able to specify that the date is in fact in a different time zone. I don't want to convert the date into my time zone because the date is already in my time zone. I just want to set the date to that time zone.

Thanks.

**Comment by georgysavva** [comment]
Sorry for the very late reply, is there still a problem?
