### ISSUE TITLE
Does scany support "SELECT * <...>" queries?

### ISSUE THREAD

**Issue by inliquid** [georgysavva/scany#79]
Documentation says the following:
>In terms of scanning and mapping abilities, scany provides all [features](https://github.com/georgysavva/scany#features) of sqlx

However I can't find any example of using scany with "select *" queries like in case of `sqlx`:
```go
    // Query the database, storing results in a []Person (wrapped in []interface{})
    people := []Person{}
    db.Select(&people, "SELECT * FROM person ORDER BY first_name ASC")
```

**Comment by georgysavva** [comment]
Hello! 
You can use `"SELECT *"` with scany, there so no distinction on scany side. It's the same as you would list all columns manually in the `SELECT` statement. 
It's true as long as there a corresponding struct field for _all_ columns in that table.

**Comment by inliquid** [comment]
Thank you!
