### ISSUE TITLE
Scanning to a nested structure

### ISSUE THREAD

**Issue by olezhek28** [georgysavva/scany#92]
Hello. I have a question. I have nested structure. Can I scan the result of a query into an Event struct if I have struct tags?

**My structs:**
```
// EventInfo ...
type EventInfo struct {
	Title     string     `db:"title"`
	Date      *time.Time `db:"date"`
	Owner     string     `db:"owner"`
	CreatedAt *time.Time `db:"created_at"`
}

// Event ...
type Event struct {
	ID int64 `db:"id"`
	EventInfo EventInfo
}
```

**My query:**

```
builder := sq.Select("id, title, date, owner, created_at").
		PlaceholderFormat(sq.Dollar).
		From(table.Event).
		Where(sq.GtOrEq{"date": utils.BeginningOfDay(date)}).
		Where(sq.LtOrEq{"date": utils.EndOfDay(date)})
```

**Comment by georgysavva** [comment]
Hi. You definitely can!
Here is the docs part explaining how to do that:
https://pkg.go.dev/github.com/georgysavva/scany@v1.1.0/dbscan#hdr-Reusing_structs

If you still have questions - feel free to reach out again, including the exact SQL query text (not the builder) and how you call `scany` API.

**Comment by olezhek28** [comment]
Thanks for the answer! However, I still have a question. Below are a few more details. I want to scan result from one table into two structures.

**My table:**
```
create table event
(
    id         bigserial primary key,
    title      text      not null,
    date       timestamp not null,
    owner      text      not null,
    created_at timestamp not null default now(),
    updated_at   timestamp
);
```

**My model:**
```
// EventInfo ...
type EventInfo struct {
	Title string     `db:"title"`
	Date  *time.Time `db:"date"`
	Owner string     `db:"owner"`
}

// Event ...
type Event struct {
	ID        int64 `db:"id"`
	EventInfo EventInfo
	CreatedAt *time.Time `db:"created_at"`
	UpdatedAt *time.Time `db:"updated_at"`
}
```

**My SQL:**
```
SELECT id, title, date, owner, created_at, updated_at FROM event WHERE date >= '2022-08-14 00:00:00 +0000' AND date <= '2022-08-14 23:59:59.999999999 +0000'
```

**My error:**
`"error": "scany: column: 'title': no corresponding field found, or it's unexported in model.Event",`

**Comment by georgysavva** [comment]
The problem is that the EventInfo field is nested, and by default, scany expects all columns corresponding to the inner fields to have the "event_info." prefix. To solve this issue, you have three options.

1. Make EventInfo field embedded, not nested. This way scany won't expect any prefix for inner fields:
```go
type Event struct {
	ID        int64 `db:"id"`
        EventInfo
	CreatedAt *time.Time `db:"created_at"`
	UpdatedAt *time.Time `db:"updated_at"`
}
```

2. Explicitly set an empty prefix for the EventInfo field:
```go
type Event struct {
	ID        int64 `db:"id"`
	EventInfo EventInfo `db:""`
	CreatedAt *time.Time `db:"created_at"`
	UpdatedAt *time.Time `db:"updated_at"`
}
```

3. Change column aliases in your SELECT query:
```
SELECT id, title "event_info.title", date "event_info.date", owner "event_info.owner", created_at, updated_at FROM event WHERE date >= '2022-08-14 00:00:00 +0000' AND date <= '2022-08-14 23:59:59.999999999 +0000'
```

I hope that helps.

**Comment by olezhek28** [comment]
Thanks a lot! It helped me.
